site_name: Publisher for MkDocs
site_url: https://mkusz.github.io/mkdocs-publisher
site_author: Maciej 'maQ' Kusz
site_description: Publishing plugin for MkDocs
copyright: >
  &copy; 2023 Maciej 'maQ' Kusz

repo_name: mkusz/mkdocs-publisher
repo_url: https://github.com/mkusz/mkdocs-publisher
edit_uri: edit/main/mkdocs_publisher_docs

docs_dir: mkdocs_publisher_docs
site_dir: docs

use_directory_urls: true
strict: true

dev_addr: 127.0.0.1:8666

extra:
  homepage: https://mkusz.github.io/mkdocs-publisher

extra_css:
  - assets/stylesheets/publisher.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js

watch:
  - overrides

theme:
  name: material
  language: en
  font: Lato
  custom_dir: overrides
  logo: publisher_logo.png
  favicon: publisher_icon.png

  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: orange
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: orange
      accent: orange

  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.footer  # Prev/Next page
    - navigation.tracking  # Anchor tracking
    - navigation.top  # Back to top
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - pub-debugger:
      console_log:
        enabled: true
        filter_logger_names:
          - mkdocs.plugins
          - mkdocs.structure.files
      file_log:
        filter_logger_names:
          - mkdocs.plugins
          - mkdocs.structure.files
  - search
  - pub-obsidian
  - pub-blog:
      blog_dir: 04_blog
  - pub-social
  - pub-meta
  - pub-minifier
